// Lista de países jogáveis: Europa completa (exceto microestados com
// população abaixo de ~100 mil) + top 10 por população na Ásia e nas
// Américas. Populações aproximadas, valores públicos gerais, apenas
// para referência inicial (não usadas ainda por nenhuma mecânica de jogo).

module.exports = [
  // Europa
  { name: 'Albânia', code: 'AL', continent: 'Europa', population: 2800000 },
  { name: 'Áustria', code: 'AT', continent: 'Europa', population: 9100000 },
  { name: 'Bielorrússia', code: 'BY', continent: 'Europa', population: 9100000 },
  { name: 'Bélgica', code: 'BE', continent: 'Europa', population: 11700000 },
  { name: 'Bósnia e Herzegovina', code: 'BA', continent: 'Europa', population: 3200000 },
  { name: 'Bulgária', code: 'BG', continent: 'Europa', population: 6400000 },
  { name: 'Croácia', code: 'HR', continent: 'Europa', population: 3900000 },
  { name: 'Chipre', code: 'CY', continent: 'Europa', population: 1300000 },
  { name: 'Chéquia', code: 'CZ', continent: 'Europa', population: 10900000 },
  { name: 'Dinamarca', code: 'DK', continent: 'Europa', population: 5900000 },
  { name: 'Estónia', code: 'EE', continent: 'Europa', population: 1300000 },
  { name: 'Finlândia', code: 'FI', continent: 'Europa', population: 5600000 },
  { name: 'França', code: 'FR', continent: 'Europa', population: 68000000 },
  { name: 'Alemanha', code: 'DE', continent: 'Europa', population: 84500000 },
  { name: 'Grécia', code: 'GR', continent: 'Europa', population: 10400000 },
  { name: 'Hungria', code: 'HU', continent: 'Europa', population: 9600000 },
  { name: 'Islândia', code: 'IS', continent: 'Europa', population: 400000 },
  { name: 'Irlanda', code: 'IE', continent: 'Europa', population: 5100000 },
  { name: 'Itália', code: 'IT', continent: 'Europa', population: 58900000 },
  { name: 'Kosovo', code: 'XK', continent: 'Europa', population: 1600000 },
  { name: 'Letónia', code: 'LV', continent: 'Europa', population: 1800000 },
  { name: 'Lituânia', code: 'LT', continent: 'Europa', population: 2700000 },
  { name: 'Luxemburgo', code: 'LU', continent: 'Europa', population: 700000 },
  { name: 'Malta', code: 'MT', continent: 'Europa', population: 500000 },
  { name: 'Moldávia', code: 'MD', continent: 'Europa', population: 2500000 },
  { name: 'Montenegro', code: 'ME', continent: 'Europa', population: 600000 },
  { name: 'Países Baixos', code: 'NL', continent: 'Europa', population: 17900000 },
  { name: 'Macedónia do Norte', code: 'MK', continent: 'Europa', population: 1800000 },
  { name: 'Noruega', code: 'NO', continent: 'Europa', population: 5500000 },
  { name: 'Polónia', code: 'PL', continent: 'Europa', population: 37600000 },
  { name: 'Portugal', code: 'PT', continent: 'Europa', population: 10500000 },
  { name: 'Roménia', code: 'RO', continent: 'Europa', population: 19000000 },
  { name: 'Rússia', code: 'RU', continent: 'Europa', population: 143800000 },
  { name: 'Sérvia', code: 'RS', continent: 'Europa', population: 6600000 },
  { name: 'Eslováquia', code: 'SK', continent: 'Europa', population: 5400000 },
  { name: 'Eslovénia', code: 'SI', continent: 'Europa', population: 2100000 },
  { name: 'Espanha', code: 'ES', continent: 'Europa', population: 47600000 },
  { name: 'Suécia', code: 'SE', continent: 'Europa', population: 10600000 },
  { name: 'Suíça', code: 'CH', continent: 'Europa', population: 8800000 },
  { name: 'Ucrânia', code: 'UA', continent: 'Europa', population: 36700000 },
  { name: 'Reino Unido', code: 'GB', continent: 'Europa', population: 68300000 },

  // Ásia (top 10 por população)
  { name: 'China', code: 'CN', continent: 'Ásia', population: 1410000000 },
  { name: 'Índia', code: 'IN', continent: 'Ásia', population: 1430000000 },
  { name: 'Indonésia', code: 'ID', continent: 'Ásia', population: 280000000 },
  { name: 'Paquistão', code: 'PK', continent: 'Ásia', population: 240000000 },
  { name: 'Bangladesh', code: 'BD', continent: 'Ásia', population: 173000000 },
  { name: 'Japão', code: 'JP', continent: 'Ásia', population: 123000000 },
  { name: 'Filipinas', code: 'PH', continent: 'Ásia', population: 117000000 },
  { name: 'Vietname', code: 'VN', continent: 'Ásia', population: 99000000 },
  { name: 'Irão', code: 'IR', continent: 'Ásia', population: 89000000 },
  { name: 'Turquia', code: 'TR', continent: 'Ásia', population: 85000000 },

  // Américas (top 10 por população)
  { name: 'Estados Unidos', code: 'US', continent: 'Américas', population: 335000000 },
  { name: 'Brasil', code: 'BR', continent: 'Américas', population: 216000000 },
  { name: 'México', code: 'MX', continent: 'Américas', population: 128000000 },
  { name: 'Colômbia', code: 'CO', continent: 'Américas', population: 52000000 },
  { name: 'Argentina', code: 'AR', continent: 'Américas', population: 46000000 },
  { name: 'Canadá', code: 'CA', continent: 'Américas', population: 39000000 },
  { name: 'Peru', code: 'PE', continent: 'Américas', population: 34000000 },
  { name: 'Venezuela', code: 'VE', continent: 'Américas', population: 28000000 },
  { name: 'Chile', code: 'CL', continent: 'Américas', population: 19600000 },
  { name: 'Equador', code: 'EC', continent: 'Américas', population: 18000000 },
];
