// Playable country list: all of Europe (except microstates with
// population below ~100k) + top 10 by population in Asia and the
// Americas. Populations are rounded, general public figures, for
// initial reference only (not yet used by any game mechanic).

module.exports = [
  // Europe
  { name: 'Albania', code: 'AL', continent: 'Europe', population: 2800000 },
  { name: 'Austria', code: 'AT', continent: 'Europe', population: 9100000 },
  { name: 'Belarus', code: 'BY', continent: 'Europe', population: 9100000 },
  { name: 'Belgium', code: 'BE', continent: 'Europe', population: 11700000 },
  { name: 'Bosnia and Herzegovina', code: 'BA', continent: 'Europe', population: 3200000 },
  { name: 'Bulgaria', code: 'BG', continent: 'Europe', population: 6400000 },
  { name: 'Croatia', code: 'HR', continent: 'Europe', population: 3900000 },
  { name: 'Cyprus', code: 'CY', continent: 'Europe', population: 1300000 },
  { name: 'Czechia', code: 'CZ', continent: 'Europe', population: 10900000 },
  { name: 'Denmark', code: 'DK', continent: 'Europe', population: 5900000 },
  { name: 'Estonia', code: 'EE', continent: 'Europe', population: 1300000 },
  { name: 'Finland', code: 'FI', continent: 'Europe', population: 5600000 },
  { name: 'France', code: 'FR', continent: 'Europe', population: 68000000 },
  { name: 'Germany', code: 'DE', continent: 'Europe', population: 84500000 },
  { name: 'Greece', code: 'GR', continent: 'Europe', population: 10400000 },
  { name: 'Hungary', code: 'HU', continent: 'Europe', population: 9600000 },
  { name: 'Iceland', code: 'IS', continent: 'Europe', population: 400000 },
  { name: 'Ireland', code: 'IE', continent: 'Europe', population: 5100000 },
  { name: 'Italy', code: 'IT', continent: 'Europe', population: 58900000 },
  { name: 'Kosovo', code: 'XK', continent: 'Europe', population: 1600000 },
  { name: 'Latvia', code: 'LV', continent: 'Europe', population: 1800000 },
  { name: 'Lithuania', code: 'LT', continent: 'Europe', population: 2700000 },
  { name: 'Luxembourg', code: 'LU', continent: 'Europe', population: 700000 },
  { name: 'Malta', code: 'MT', continent: 'Europe', population: 500000 },
  { name: 'Moldova', code: 'MD', continent: 'Europe', population: 2500000 },
  { name: 'Montenegro', code: 'ME', continent: 'Europe', population: 600000 },
  { name: 'Netherlands', code: 'NL', continent: 'Europe', population: 17900000 },
  { name: 'North Macedonia', code: 'MK', continent: 'Europe', population: 1800000 },
  { name: 'Norway', code: 'NO', continent: 'Europe', population: 5500000 },
  { name: 'Poland', code: 'PL', continent: 'Europe', population: 37600000 },
  { name: 'Portugal', code: 'PT', continent: 'Europe', population: 10500000 },
  { name: 'Romania', code: 'RO', continent: 'Europe', population: 19000000 },
  { name: 'Russia', code: 'RU', continent: 'Europe', population: 143800000 },
  { name: 'Serbia', code: 'RS', continent: 'Europe', population: 6600000 },
  { name: 'Slovakia', code: 'SK', continent: 'Europe', population: 5400000 },
  { name: 'Slovenia', code: 'SI', continent: 'Europe', population: 2100000 },
  { name: 'Spain', code: 'ES', continent: 'Europe', population: 47600000 },
  { name: 'Sweden', code: 'SE', continent: 'Europe', population: 10600000 },
  { name: 'Switzerland', code: 'CH', continent: 'Europe', population: 8800000 },
  { name: 'Ukraine', code: 'UA', continent: 'Europe', population: 36700000 },
  { name: 'United Kingdom', code: 'GB', continent: 'Europe', population: 68300000 },

  // Asia (top 10 by population)
  { name: 'China', code: 'CN', continent: 'Asia', population: 1410000000 },
  { name: 'India', code: 'IN', continent: 'Asia', population: 1430000000 },
  { name: 'Indonesia', code: 'ID', continent: 'Asia', population: 280000000 },
  { name: 'Pakistan', code: 'PK', continent: 'Asia', population: 240000000 },
  { name: 'Bangladesh', code: 'BD', continent: 'Asia', population: 173000000 },
  { name: 'Japan', code: 'JP', continent: 'Asia', population: 123000000 },
  { name: 'Philippines', code: 'PH', continent: 'Asia', population: 117000000 },
  { name: 'Vietnam', code: 'VN', continent: 'Asia', population: 99000000 },
  { name: 'Iran', code: 'IR', continent: 'Asia', population: 89000000 },
  { name: 'Turkey', code: 'TR', continent: 'Asia', population: 85000000 },

  // Americas (top 10 by population)
  { name: 'United States', code: 'US', continent: 'Americas', population: 335000000 },
  { name: 'Brazil', code: 'BR', continent: 'Americas', population: 216000000 },
  { name: 'Mexico', code: 'MX', continent: 'Americas', population: 128000000 },
  { name: 'Colombia', code: 'CO', continent: 'Americas', population: 52000000 },
  { name: 'Argentina', code: 'AR', continent: 'Americas', population: 46000000 },
  { name: 'Canada', code: 'CA', continent: 'Americas', population: 39000000 },
  { name: 'Peru', code: 'PE', continent: 'Americas', population: 34000000 },
  { name: 'Venezuela', code: 'VE', continent: 'Americas', population: 28000000 },
  { name: 'Chile', code: 'CL', continent: 'Americas', population: 19600000 },
  { name: 'Ecuador', code: 'EC', continent: 'Americas', population: 18000000 },
];
